### ISSUE TITLE
Makes gh-pages as default branch

### ISSUE THREAD

**Issue by cognitom** [riot/examples#12]
Is it OK?
I think we don't have to manage both `master` and `gh-pages`. We could drop `master` after the default changed.

**Comment by cognitom** [comment]
@rsbondi thoughts?

**Comment by rsbondi** [comment]
`master` seems redundant to me.  How do you plan to verify PRs before merging?

**Comment by cognitom** [comment]
We could add Travis to run the test in each sub directories.
And this repo is not a **library**, so we don't have to be nervous, do we?

**Comment by cognitom** [comment]
@rsbondi I've just added `.travis.yml` to this repo. It'll help us to verify PRs :-)

The point is using build matrix for each sub-directory. It works fine.

``` yml
language: node_js
node_js:
  - "0.12.0"
env:
  - TEST_DIR=router-page-switcher
  - TEST_DIR=timer
script: cd $TEST_DIR && npm install && npm test
```

cc @aMarCruz @GianlucaGuarini
